### PR TITLE
Changed author page

### PR DESCRIPTION
**Pull request by AdvaitChandorkar07**
Changed the authors as in issue #68 with one book shown for each author

### CODE REVIEW

**Comment by AdvaitChandorkar07** [comment]
also i removed nan as an authour altogether

**Comment by AdvaitChandorkar07** [comment]
I am not showing NAN in the section but if the image URL is not working I have displayed text no book cover

**Comment by AdvaitChandorkar07** [comment]
I am not showing NAN in the section  of authors but if the image URL is not working I have displayed text no book cover

**Comment by jchefdeville** [comment]
I'll have a look tomorrow 🙂
Thx for your contribution

**Review by jchefdeville — APPROVED** [review]

**Pull request merged**
