### PR TITLE
Pages

### PR DESCRIPTION
**Pull request by SebastienBelleville**
I'm not too sure how to push #25 again, but this is my main.py file with all the functions added back in. I also updated the front end to display 30 results per page, with buttons taking you to the next and previous pages.

### CODE REVIEW

**Comment by SebastienBelleville** [comment]
i kept your printTopBooksByReview function, only changed the brec() and  displayTopRev

**Comment by jchefdeville** [comment]
I pushed #25 on my side. I didn't pull first I think.. I dunno what happened otherwise
"i kept your printTopBooksByReview function, only changed the brec() and displayTopRev" : you didn't have them on your side ?

**Comment by SebastienBelleville** [comment]
I'm sorry for the confusion, I thought you were asking me to push something again. This was a push for some front end changes I made to add buttons to the html and css file. I have everything that is currently in main.py

**Comment by SebastienBelleville** [comment]
I'm fairly new to github but I'm trying to make sure I don't accidentally break the repo, thank you for your patience

**Comment by jchefdeville** [comment]
I'm trying to not break everything aswell, pretty new on GitHub and python :)

**Pull request merged**
